[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "chromium", "chromedriver"]
nixLibs = ["glibc", "nss", "nspr", "atk", "at-spi2-atk", "cups", "dbus", "expat", "xorg.libxcb", "libxkbcommon", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "pango", "cairo", "alsa-lib", "mesa", "gtk3"]

[phases.install]
cmds = [
  "pip install -r requirements.txt --break-system-packages --no-cache-dir",
  "mkdir -p /tmp/.X11-unix /tmp/.chrome /tmp/.config/chromium",
  "chmod -R 1777 /tmp/.X11-unix /tmp/.chrome /tmp/.config",
  "mkdir -p /app/downloads"
]

[phases.build]
cmds = [
  "echo 'Build complete'",
  "echo 'Chrome location:' $(which chromium)",
  "echo 'ChromeDriver location:' $(which chromedriver)"
]

[start]
cmd = "DISPLAY=:99 CHROME_BIN=$(which chromium) CHROMEDRIVER_PATH=$(which chromedriver) HOME=/tmp TMPDIR=/tmp uvicorn app:app --host 0.0.0.0 --port $PORT"
